name: Weather Data Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # Ежедневно в 6:00 UTC
  workflow_dispatch:

env:
  OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

jobs:
  weather-analysis:
    runs-on: ubuntu-latest
    steps:
      # Шаг для клонирования репозитория
      - uses: actions/checkout@v3
      
      # Шаг для установки Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      # Шаг для установки зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project2/requirements.txt  # Используем requirements.txt из папки project2
      
      # Шаг для сбора данных о погоде
      - name: Fetch Weather Data
        run: python project2/scripts/fetch_weather.py  # Указываем путь к скрипту в project2/scripts/

      # Шаг для анализа данных о погоде
      - name: Analyze Weather Trends
        run: python project2/scripts/analyze_weather.py  # Указываем путь к скрипту в project2/scripts/

      # Шаг для генерации визуализаций
      - name: Generate Visualizations
        run: python project2/scripts/visualize_weather.py  # Указываем путь к скрипту в project2/scripts/
      
      # Шаг для коммита и пуша изменений
      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add project2/reports/ project2/data/  # Указываем пути к директориям отчетов и данных в project2
          git commit -m "Daily Weather Data Analysis" || exit 0
          git push

